### ISSUE TITLE
Build file examples don’t show up

### ISSUE THREAD

**Issue by fifthposition** [spring-guides/gs-client-side-load-balancing#1]
<img width="756" alt="gradle" src="https://cloud.githubusercontent.com/assets/115082/14802280/b4c7f7ec-0b15-11e6-9eeb-f02b4fb1f46a.png">

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-client-side-load-balancing/commit/902b27f7069ad689da855958f87fb751b14539d3
